# Generated by Django 4.2.14 on 2024-08-06 12:25

import blog.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('prep_time', models.PositiveIntegerField(default=15, validators=[blog.models.validate_nonzero, django.core.validators.MaxValueValidator(300)])),
                ('cooking_time', models.PositiveIntegerField(default=15, validators=[blog.models.validate_nonzero, django.core.validators.MaxValueValidator(600)])),
                ('servings', models.PositiveIntegerField(default=1, validators=[blog.models.validate_nonzero, django.core.validators.MaxValueValidator(50)])),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='recipe_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
