# Generated by Django 4.2.14 on 2024-08-06 14:19

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories_carbs',
            field=models.PositiveIntegerField(default=0, help_text='Calories from carbohydrates', validators=[blog.models.validate_nonzero]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories_fats',
            field=models.PositiveIntegerField(default=0, help_text='Calories from fats', validators=[blog.models.validate_nonzero]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories_protein',
            field=models.PositiveIntegerField(default=0, help_text='Calories from protein', validators=[blog.models.validate_nonzero]),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_calories',
            field=models.PositiveIntegerField(default=0, help_text='Total calories in the recipe', validators=[blog.models.validate_nonzero]),
        ),
    ]
