# Generated by Django 4.2.14 on 2024-08-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_recipe_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='profile_image',
        ),
    ]
