# Generated by Django 4.2.14 on 2024-08-14 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_recipe_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='excerpt',
        ),
    ]
