# Generated by Django 4.2.14 on 2024-11-18 16:14

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_recipe_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories_carbs',
            field=models.PositiveIntegerField(default=1, help_text='Calories from carbohydrates', validators=[blog.models.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories_fats',
            field=models.PositiveIntegerField(default=1, help_text='Calories from fats', validators=[blog.models.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories_protein',
            field=models.PositiveIntegerField(default=1, help_text='Calories from protein', validators=[blog.models.validate_nonzero]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_calories',
            field=models.PositiveIntegerField(default=1, help_text='Total calories in the recipe', validators=[blog.models.validate_nonzero]),
        ),
    ]
